// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: featureflag.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagsRequest) Reset() {
	*x = GetFlagsRequest{}
	mi := &file_featureflag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagsRequest) ProtoMessage() {}

func (x *GetFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_featureflag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagsRequest.ProtoReflect.Descriptor instead.
func (*GetFlagsRequest) Descriptor() ([]byte, []int) {
	return file_featureflag_proto_rawDescGZIP(), []int{0}
}

type GetFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         map[string]string      `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagsResponse) Reset() {
	*x = GetFlagsResponse{}
	mi := &file_featureflag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagsResponse) ProtoMessage() {}

func (x *GetFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_featureflag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagsResponse.ProtoReflect.Descriptor instead.
func (*GetFlagsResponse) Descriptor() ([]byte, []int) {
	return file_featureflag_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlagsResponse) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

var File_featureflag_proto protoreflect.FileDescriptor

const file_featureflag_proto_rawDesc = "" +
	"\n" +
	"\x11featureflag.proto\x12\vfeatureflag\"\x11\n" +
	"\x0fGetFlagsRequest\"\x8c\x01\n" +
	"\x10GetFlagsResponse\x12>\n" +
	"\x05flags\x18\x01 \x03(\v2(.featureflag.GetFlagsResponse.FlagsEntryR\x05flags\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012]\n" +
	"\x12FeatureFlagService\x12G\n" +
	"\bGetFlags\x12\x1c.featureflag.GetFlagsRequest\x1a\x1d.featureflag.GetFlagsResponseB'Z%github.com/docpilot/feature-flag/grpcb\x06proto3"

var (
	file_featureflag_proto_rawDescOnce sync.Once
	file_featureflag_proto_rawDescData []byte
)

func file_featureflag_proto_rawDescGZIP() []byte {
	file_featureflag_proto_rawDescOnce.Do(func() {
		file_featureflag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_featureflag_proto_rawDesc), len(file_featureflag_proto_rawDesc)))
	})
	return file_featureflag_proto_rawDescData
}

var file_featureflag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_featureflag_proto_goTypes = []any{
	(*GetFlagsRequest)(nil),  // 0: featureflag.GetFlagsRequest
	(*GetFlagsResponse)(nil), // 1: featureflag.GetFlagsResponse
	nil,                      // 2: featureflag.GetFlagsResponse.FlagsEntry
}
var file_featureflag_proto_depIdxs = []int32{
	2, // 0: featureflag.GetFlagsResponse.flags:type_name -> featureflag.GetFlagsResponse.FlagsEntry
	0, // 1: featureflag.FeatureFlagService.GetFlags:input_type -> featureflag.GetFlagsRequest
	1, // 2: featureflag.FeatureFlagService.GetFlags:output_type -> featureflag.GetFlagsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_featureflag_proto_init() }
func file_featureflag_proto_init() {
	if File_featureflag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_featureflag_proto_rawDesc), len(file_featureflag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_featureflag_proto_goTypes,
		DependencyIndexes: file_featureflag_proto_depIdxs,
		MessageInfos:      file_featureflag_proto_msgTypes,
	}.Build()
	File_featureflag_proto = out.File
	file_featureflag_proto_goTypes = nil
	file_featureflag_proto_depIdxs = nil
}
