# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import aiworker_pb2 as aiworker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aiworker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiWorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
                '/aiworker.AiWorkerService/IndexDocument',
                request_serializer=aiworker__pb2.IndexDocumentRequest.SerializeToString,
                response_deserializer=aiworker__pb2.IndexDocumentResponse.FromString,
                _registered_method=True)
        self.Ask = channel.unary_unary(
                '/aiworker.AiWorkerService/Ask',
                request_serializer=aiworker__pb2.AskRequest.SerializeToString,
                response_deserializer=aiworker__pb2.AskResponse.FromString,
                _registered_method=True)
        self.AskStream = channel.unary_stream(
                '/aiworker.AiWorkerService/AskStream',
                request_serializer=aiworker__pb2.AskRequest.SerializeToString,
                response_deserializer=aiworker__pb2.AskStreamResponse.FromString,
                _registered_method=True)
        self.SuggestQuestions = channel.unary_unary(
                '/aiworker.AiWorkerService/SuggestQuestions',
                request_serializer=aiworker__pb2.SuggestQuestionsRequest.SerializeToString,
                response_deserializer=aiworker__pb2.SuggestQuestionsResponse.FromString,
                _registered_method=True)
        self.SummarizeDocument = channel.unary_unary(
                '/aiworker.AiWorkerService/SummarizeDocument',
                request_serializer=aiworker__pb2.SummarizeDocumentRequest.SerializeToString,
                response_deserializer=aiworker__pb2.SummarizeDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/aiworker.AiWorkerService/DeleteDocument',
                request_serializer=aiworker__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=aiworker__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)


class AiWorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def IndexDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestQuestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=aiworker__pb2.IndexDocumentRequest.FromString,
                    response_serializer=aiworker__pb2.IndexDocumentResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=aiworker__pb2.AskRequest.FromString,
                    response_serializer=aiworker__pb2.AskResponse.SerializeToString,
            ),
            'AskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskStream,
                    request_deserializer=aiworker__pb2.AskRequest.FromString,
                    response_serializer=aiworker__pb2.AskStreamResponse.SerializeToString,
            ),
            'SuggestQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestQuestions,
                    request_deserializer=aiworker__pb2.SuggestQuestionsRequest.FromString,
                    response_serializer=aiworker__pb2.SuggestQuestionsResponse.SerializeToString,
            ),
            'SummarizeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeDocument,
                    request_deserializer=aiworker__pb2.SummarizeDocumentRequest.FromString,
                    response_serializer=aiworker__pb2.SummarizeDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=aiworker__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=aiworker__pb2.DeleteDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiworker.AiWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiworker.AiWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiWorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiworker.AiWorkerService/IndexDocument',
            aiworker__pb2.IndexDocumentRequest.SerializeToString,
            aiworker__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiworker.AiWorkerService/Ask',
            aiworker__pb2.AskRequest.SerializeToString,
            aiworker__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiworker.AiWorkerService/AskStream',
            aiworker__pb2.AskRequest.SerializeToString,
            aiworker__pb2.AskStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiworker.AiWorkerService/SuggestQuestions',
            aiworker__pb2.SuggestQuestionsRequest.SerializeToString,
            aiworker__pb2.SuggestQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiworker.AiWorkerService/SummarizeDocument',
            aiworker__pb2.SummarizeDocumentRequest.SerializeToString,
            aiworker__pb2.SummarizeDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiworker.AiWorkerService/DeleteDocument',
            aiworker__pb2.DeleteDocumentRequest.SerializeToString,
            aiworker__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
