# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiworker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aiworker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61iworker.proto\x12\x08\x61iworker\"L\n\x14IndexDocumentRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x1f\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x0f.aiworker.Chunk\"<\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"/\n\x15IndexDocumentResponse\x12\x16\n\x0eindexed_chunks\x18\x01 \x01(\x05\"H\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x18\n\x0b\x64ocument_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_document_id\"\x1d\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\",\n\x15\x44\x65leteDocumentRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\")\n\x16\x44\x65leteDocumentResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xec\x01\n\x0f\x41iWorkerService\x12P\n\rIndexDocument\x12\x1e.aiworker.IndexDocumentRequest\x1a\x1f.aiworker.IndexDocumentResponse\x12\x32\n\x03\x41sk\x12\x14.aiworker.AskRequest\x1a\x15.aiworker.AskResponse\x12S\n\x0e\x44\x65leteDocument\x12\x1f.aiworker.DeleteDocumentRequest\x1a .aiworker.DeleteDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiworker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDEXDOCUMENTREQUEST']._serialized_start=28
  _globals['_INDEXDOCUMENTREQUEST']._serialized_end=104
  _globals['_CHUNK']._serialized_start=106
  _globals['_CHUNK']._serialized_end=166
  _globals['_INDEXDOCUMENTRESPONSE']._serialized_start=168
  _globals['_INDEXDOCUMENTRESPONSE']._serialized_end=215
  _globals['_ASKREQUEST']._serialized_start=217
  _globals['_ASKREQUEST']._serialized_end=289
  _globals['_ASKRESPONSE']._serialized_start=291
  _globals['_ASKRESPONSE']._serialized_end=320
  _globals['_DELETEDOCUMENTREQUEST']._serialized_start=322
  _globals['_DELETEDOCUMENTREQUEST']._serialized_end=366
  _globals['_DELETEDOCUMENTRESPONSE']._serialized_start=368
  _globals['_DELETEDOCUMENTRESPONSE']._serialized_end=409
  _globals['_AIWORKERSERVICE']._serialized_start=412
  _globals['_AIWORKERSERVICE']._serialized_end=648
# @@protoc_insertion_point(module_scope)
