spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docpilot
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

ai-worker:
  base-url: http://localhost:8000